---
- id: mdsf-format
  name: mdsf format
  entry: mdsf format
  description: Run 'mdsf format' on changed files
  require_serial: true
  types: [markdown]
  # TODO: switch to "rust" once pre-commit supports cargo workspaces
  language: system
- id: mdsf-verify
  name: mdsf verify
  entry: mdsf verify
  description: Run 'mdsf verify' on changed files
  require_serial: true
  types: [markdown]
  # TODO: switch to "rust" once pre-commit supports cargo workspaces
  language: system
