name: "setup-mdsf"
description: "Setup mdsf cli in GitHub Actions"
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: "The mdsf version to install"
    required: true
    default: ""
runs:
  using: "node20"
  main: "github-action/src/index.js"
