name: setup-mdsf
author: hougesen
description: Setup mdsf cli in GitHub Actions
branding:
  icon: code
  color: black
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The mdsf version to install. Defaults to latest version.
    required: true
    default: ""
runs:
  using: node20
  main: github-action/dist/index.js
