name: codegen
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  update-readme:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Generate stuff
        run: cargo run --package mdsf-codegen
        # A second run is needed until the readme generation is decoupled from the json-schema
      - run: cargo run --package mdsf-codegen
      - run: cargo fmt
      - run: cargo run -- format README.md
      - run: npx prettier@latest --write schemas mdsf.json README.md tools
      - uses: EndBug/add-and-commit@v9
        with:
          add: schemas mdsf.json README.md tools mdsf/
          message: "chore: updated generated code"
