name: mdsf
on:
  push:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install mdsf
        uses: hougesen/mdsf@feat/setup-mdsf-github-action
      - name: Run mdsf
        run: mdsf verify --log-level warn .
