name: mdsf
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # disabled because of an issue with crlf
          # - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install mdsf
        uses: hougesen/mdsf@fix/github-action/change-default-archive-format
      - name: Run mdsf
        run: mdsf verify --log-level warn .
