name: mdsf
on:
  push:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ matrix.os }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install mdsf
        uses: hougesen/mdsf@fix/github-action/change-default-archive-format
      - name: Run mdsf
        run: mdsf verify --log-level warn .
