name: mdsf
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install mdsf
        uses: taiki-e/install-action@v2
        with:
          tool: mdsf
      - name: Run mdsf
        run: mdsf verify .
