name: update schema
on:
  push:
    branches:
      - "main"

jobs:
  schema:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: update schema
        run: cargo run -- schema

      - name: update readme
        run: node scripts/update-supported-languages.mjs

      - name: format
        run: npx prettier --write schemas/ README.md

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update config schema"
