name: validate

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
            # TODO: remove once macos-latest is upgraded to an arm machine
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup component add rustfmt clippy
      - run: cargo fetch
      - run: cargo fmt -- --check --color always
      - run: cargo clippy

  test:
    name: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      # Used by ruff
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      # Used by biome
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      # Used by nimpretty
      - uses: jiro4989/setup-nim-action@v1

      - run: rustup toolchain install stable --profile minimal
      - run: rustup component add rustfmt clippy

      - name: Install taplo
        run: curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz  | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: Validate taplo
        run: taplo --version

      - name: Install ruff
        run: pip install ruff

      - name: Validate ruff
        run: ruff --version

      - name: Validate biome
        run: npx --yes @biomejs/biome@latest --version

      - name: Validate nimpretty
        run: nimpretty --version

      - run: cargo test
